### ISSUE TITLE
config.use seems to be broken

### ISSUE THREAD

**Issue by reuven** [avdi/quarto#28]
I'm using Ruby 2.1.2.  I cloned the Git repository, and copied the examples/orgmode-basic directory to its own directory, to avoid the overall quarto Rakefile from affecting the book's Rakefile.  I then typed

```
rake -T
```

and got the following:

```
$ rake -T
rake aborted!
NoMethodError: undefined method `use' for Quarto:Module
/Users/reuven/Downloads/orgmode-basic/Rakefile:4:in `block in <top (required)>'
/Users/reuven/.rvm/gems/ruby-2.1.2/gems/quarto-0.0.1/lib/quarto.rb:11:in `configure'
/Users/reuven/Downloads/orgmode-basic/Rakefile:3:in `<top (required)>'
/Users/reuven/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/reuven/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

I got the same result with Ruby 1.9.3.  Any suggestions?

**Comment by jschoolcraft** [comment]
I'm late to the party but I can reproduce both of the config issues:
- #28
- #26 

Gemfile:

      source 'https://rubygems.org'

      gem 'rake'
      gem 'quarto', github: 'avdi/quarto'

It's pointing to the latest commit on master:

      bundle show quarto
      /Users/jschoolcraft/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/quarto-28de735c7b07

Error:

      rake aborted!
      NoMethodError: undefined method `author=' for Quarto:Module
      /Users/jschoolcraft/code/therobotcoach/vex-tutorial/Rakefile:4:in `block in <top (required)>'
      /Users/jschoolcraft/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/quarto-0.0.1/lib/quarto.rb:11:in `configure'
      /Users/jschoolcraft/code/therobotcoach/vex-tutorial/Rakefile:3:in `<top (required)>'
      /Users/jschoolcraft/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load'
      /Users/jschoolcraft/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load_rakefile'
      /Users/jschoolcraft/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:689:in `raw_load_rakefile'
      /Users/jschoolcraft/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:94:in `block in load_rakefile'
      /Users/jschoolcraft/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
      /Users/jschoolcraft/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'
      /Users/jschoolcraft/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
      /Users/jschoolcraft/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
      /Users/jschoolcraft/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
      /Users/jschoolcraft/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
      /Users/jschoolcraft/.rbenv/versions/2.1.2/bin/rake:23:in `load'
      /Users/jschoolcraft/.rbenv/versions/2.1.2/bin/rake:23:in `<main>'

Same with use, e.g.:

      require 'quarto'

      Quarto.configure do |config|
        # config.author              = "Jeff Schoolcraft"
        # config.title               = "VEX ROBOTC Tutorial"

        config.use :markdown      # if you want to use markdown
      end

rake -T output:

      rake aborted!
      NoMethodError: undefined method `use' for Quarto:Module
      /Users/jschoolcraft/code/therobotcoach/vex-tutorial/Rakefile:7:in `block in <top (required)>'
      /Users/jschoolcraft/code/therobotcoach/vex-tutorial/Rakefile:3:in `<top (required)>'
      (See full trace by running task with --trace)

Even the default task isn't set (says `rake deliverables` should be it in the README)

      ~/c/t/vex-tutorial ❯❯❯ rake
      rake aborted!
      Don't know how to build task 'default'

      (See full trace by running task with --trace)
